name: restio
description: A simple but powerful HTTP Client for Dart inspired by OkHttp.
version: 0.3.0
homepage: https://github.com/tiagohm/restio

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  utf: ^0.9.0+5
  http_parser: ^3.1.3
  crypto: ^2.1.4
  path: ^1.6.4
  string_scanner: ^1.0.5
  mime: ^0.9.6+3
  meta: ^1.1.8
  http2: ^1.0.0
  equatable: ^1.0.1
  raw: ^0.2.0
  ip: ^0.1.1
  brotli: ^0.2.1

dev_dependencies:
  test: ^1.6.5
  effective_dart: ^1.1.2
